=== axe2016/asiaxpress/qryProdukte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="qryProdukte" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="qryProdukte">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="KeyNumber" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="ProduktNummer" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="ProductName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="150"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ProductDescription" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Category" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Category2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LieferPreis" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="LokalPreis" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="picFileName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== axe2016/asiaxpress/qryProdukte.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="qryProdukte.xsd" generated="2016-05-31T22:40:22">
<qryProdukte>
<KeyNumber>1</KeyNumber>
<ProduktNummer>1</ProduktNummer>
<ProductName>Peking-Suppe</ProductName>
<ProductDescription>scharf-sauer</ProductDescription>
<Category>Suppen</Category>
<LieferPreis>3.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>2</KeyNumber>
<ProduktNummer>2</ProduktNummer>
<ProductName>Wan-Tan Suppe</ProductName>
<Category>Suppen</Category>
<LieferPreis>3.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>3</KeyNumber>
<ProduktNummer>3</ProduktNummer>
<ProductName>Gemüsesuppe mit Glasnudeln</ProductName>
<Category>Suppen</Category>
<LieferPreis>3</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>4</KeyNumber>
<ProduktNummer>4</ProduktNummer>
<ProductName>Tom-Yam-Gai Thail. Hühnerfleischsuppe</ProductName>
<ProductDescription>scharf</ProductDescription>
<Category>Suppen</Category>
<LieferPreis>3.6</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>5</KeyNumber>
<ProduktNummer>5</ProduktNummer>
<ProductName>Tom-Yam-Gung Thail. Garnelensuppe</ProductName>
<ProductDescription>scharf</ProductDescription>
<Category>Suppen</Category>
<LieferPreis>4.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>6</KeyNumber>
<ProduktNummer>6</ProduktNummer>
<ProductName>Eierblumensuppe mit Mais und Hühnerfleisch</ProductName>
<Category>Suppen</Category>
<LieferPreis>3.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>7</KeyNumber>
<ProduktNummer>7</ProduktNummer>
<ProductName>Glasnudelnsuppe mit Hühnerfleisch</ProductName>
<Category>Suppen</Category>
<LieferPreis>3.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>8</KeyNumber>
<ProduktNummer>11</ProduktNummer>
<ProductName>Frühlingsrolle</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>3.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>9</KeyNumber>
<ProduktNummer>12</ProduktNummer>
<ProductName>Mini-Gemüserollen</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>3</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>10</KeyNumber>
<ProduktNummer>13</ProduktNummer>
<ProductName>Wan Tan gebacken</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>3.5</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>11</KeyNumber>
<ProduktNummer>14</ProduktNummer>
<ProductName>Yakitori Hühnerfleisch-Spieße</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>3.6</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>12</KeyNumber>
<ProduktNummer>15</ProduktNummer>
<ProductName>Hühnerflügeln gebacken</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>4</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>13</KeyNumber>
<ProduktNummer>17</ProduktNummer>
<ProductName>Gemüsesalat mit Dressing</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>3.6</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>14</KeyNumber>
<ProduktNummer>18</ProduktNummer>
<ProductName>Asia-Salat mit Sesam-Hühnerfleisch</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>5</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>15</KeyNumber>
<ProduktNummer>19</ProduktNummer>
<ProductName>Asia-Salat mit Tempura, gebackene Garnelen in Teig</ProductName>
<Category>Vorspeisen</Category>
<LieferPreis>6.2</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>63</KeyNumber>
<ProduktNummer>20</ProduktNummer>
<ProductName>Gemischter Gemüsesalat</ProductName>
<ProductDescription>mit Dressing (Kräuter oder Joghurt oder French)</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>3.8</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>17</KeyNumber>
<ProduktNummer>21</ProduktNummer>
<ProductName>Gemüsesalat mit Hähnchenbrust</ProductName>
<ProductDescription>mit Erdnuss-Sauce</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>5.8</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>64</KeyNumber>
<ProduktNummer>22</ProduktNummer>
<ProductName>Gemüsesalat Chicken</ProductName>
<ProductDescription>mit knusprigen Sesam-Hühnerfleisch</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>6.4</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>65</KeyNumber>
<ProduktNummer>23</ProduktNummer>
<ProductName>Gemüsesalat mit Tempura</ProductName>
<ProductDescription>Garnelen in Teig gebacken, 2 Stücke</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>7.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>66</KeyNumber>
<ProduktNummer>24</ProduktNummer>
<ProductName>Gemürsesalat Asia</ProductName>
<ProductDescription>mit Hühnerfleisch, Ente, Garnelen</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>7.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>67</KeyNumber>
<ProduktNummer>25</ProduktNummer>
<ProductName>Rindfleisch- Salat</ProductName>
<ProductDescription>sehr scharfer thailändischer Salat</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>6.4</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>16</KeyNumber>
<ProduktNummer>26</ProduktNummer>
<ProductName>Edamame</ProductName>
<ProductDescription>japanische Sojabohnen</ProductDescription>
<Category>Vorspeisen</Category>
<Category2>Salate</Category2>
<LieferPreis>3.9</LieferPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>27</KeyNumber>
<ProduktNummer>30</ProduktNummer>
<ProductName>Hühnerfleisch mit Chili, Ingwer und Knoblauch</ProductName>
<ProductDescription>sehr scharf</ProductDescription>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>18</KeyNumber>
<ProduktNummer>31</ProduktNummer>
<ProductName>Hühnerfleisch Chop- Suey</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.4</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>19</KeyNumber>
<ProduktNummer>32</ProduktNummer>
<ProductName>Hühnerfleisch Gong-Bao mit Cashewnüsse</ProductName>
<ProductDescription>scharf</ProductDescription>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>20</KeyNumber>
<ProduktNummer>33</ProduktNummer>
<ProductName>Hühnerfleisch mit scharferThai-Rotcurry</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>21</KeyNumber>
<ProduktNummer>34</ProduktNummer>
<ProductName>Hühnerfleisch gebacken mit süß-saurer Sauce</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>22</KeyNumber>
<ProduktNummer>35</ProduktNummer>
<ProductName>Hühnerfleisch mit Morcheln und Glasnudeln</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.4</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>23</KeyNumber>
<ProduktNummer>36</ProduktNummer>
<ProductName>Hähnchenkeule gebacken Thai-Rotcurry</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.6</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>24</KeyNumber>
<ProduktNummer>37</ProduktNummer>
<ProductName>Hähnchenkeule gebacken mit scharfer Hoi-Sin Sauce</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.6</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>25</KeyNumber>
<ProduktNummer>38</ProduktNummer>
<ProductName>Hähnchenkeule mit Reiswein-Sauce</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.6</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>26</KeyNumber>
<ProduktNummer>39</ProduktNummer>
<ProductName>Hühnerfleisch Saté-Spieße mit Erdnuss-Sauce</ProductName>
<Category>Hühnerfleisch</Category>
<LieferPreis>8.6</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>36</KeyNumber>
<ProduktNummer>40</ProduktNummer>
<ProductName>Rindfleisch Chop-Suey</ProductName>
<Category>Rindfleisch</Category>
<LieferPreis>9.4</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>37</KeyNumber>
<ProduktNummer>41</ProduktNummer>
<ProductName>Rindfleisch Gong-Bao</ProductName>
<ProductDescription>scharf</ProductDescription>
<Category>Rindfleisch</Category>
<LieferPreis>9.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>38</KeyNumber>
<ProduktNummer>42</ProduktNummer>
<ProductName>Rindfleisch Thai-Rotcurry</ProductName>
<ProductDescription>scharf</ProductDescription>
<Category>Rindfleisch</Category>
<LieferPreis>9.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>39</KeyNumber>
<ProduktNummer>43</ProduktNummer>
<ProductName>Rindfleisch mit Zwiebeln</ProductName>
<ProductDescription>scharf</ProductDescription>
<Category>Rindfleisch</Category>
<LieferPreis>9.4</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>40</KeyNumber>
<ProduktNummer>44</ProduktNummer>
<ProductName>Sukiyaki ,Rindfleisch mit Morcheln und Glasnudeln</ProductName>
<Category>Rindfleisch</Category>
<LieferPreis>9.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>41</KeyNumber>
<ProduktNummer>45</ProduktNummer>
<ProductName>Rindfleisch mit Chili und Knoblauch</ProductName>
<ProductDescription>sehr scharf</ProductDescription>
<Category>Rindfleisch</Category>
<LieferPreis>9.5</LieferPreis>
<LokalPreis>0</LokalPreis>
</qryProdukte>
<qryProdukte>
<KeyNumber>28</KeyNumber>
<ProduktNummer>50</ProduktNummer>
